### ISSUE TITLE
Decimal rounding

### ISSUE THREAD

**Issue by mnot** [httpwg/structured-header-tests#32]
... probably needs some explicit tests.

**Comment by mnot** [comment]
The problem here is that this is purely a serialisation issue, and serialisation is currently tested in terms of the wire form, not all possible inputs.

So to do this, we'd need to have a new kind of test; one that took input that's not valid on the wire but (sometimes) resulted in wire-valid serialisation. 

Besides decimals, it seems like this would also help with making sure that errors were generated when non-ascii got into string, etc.

**Comment by phluid61** [comment]
I have trouble testing invalid serialisations because I implemented the SH data models as first class types, so my Decimal can never contain something that isn't 12.3 decimal digits.  It says _"Given a decimal_number_ \[sic] _as input_decimal, return an ASCII string suitable for use in a HTTP header value."_ which I took to mean, the input is already in the SH data model and therefore sanitised.

The place where I currently have the equivalent failure is in the "cast to SH" step, which isn't explicitly discussed in the draft;  I sort of teased it out from a combination of the ABNF and the serialisation algorithms.

I realise that we similarly never test the "fail serialisation" branches of other algorithms that have them ([key](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#ser-key), for example).

**Comment by mnot** [comment]
This might be a separate test corpus, then.

**Comment by phluid61** [comment]
Yeah, I think so. The "(casting and) serialising an arbitrary native value" tests.

**Comment by phluid61** [comment]
We could fake it with a new rule: if there's no/null "raw" value, the test case either must_fail, or serialises expected⇒canonical.

It's a messy misuse of the word "expected" in a test case, but it gets the values in there.
